Feat/op profile edit
socious-io/web-app-v2 pull request #310
Opened 2024-01-01 19:56 UTC by marjan-ara

2024-01-05 10:36 UTC, bastantebom commented on env.tmp
Do we need this file? I think we need to delete this

2024-01-05 10:43 UTC, bastantebom commented on src/Nowruz/modules/general/components/iconDropDown/useIconDropDown.tsx
> +            ? `profile/users/${(current.meta as UserMeta).username}/view`
I think I asked to refactor this before, since that PR has been closed then it revert back from the original

2024-01-05 10:49 UTC, bastantebom commented on src/Nowruz/modules/userProfile/components/profileHeader/desktopHeader.tsx
> +  const username = type === 'users' ? `@${(identity as User).username}` : `@${(identity as Organization).shortname}`;
```suggestion
  Can this be extracted as a helper or util function? This has been used in multiple instances all throughout the application. Something like this:
  
  export function getNameAndUsername(identity: User | Organization): [string, string] {
  if ('first_name' in identity) {
    // Handle User type
    const user = identity as User;
    return [
      `${user.first_name} ${user.last_name}`,
      `@${user.username}`
    ];
  } else {
    // Handle Organization type
    const org = identity as Organization;
    return [org.name, `@${org.shortname}`];
  }
}

// Usage:
const [name, username] = getNameAndUsername(identity);
```

2024-01-05 10:49 UTC, bastantebom commented on src/Nowruz/modules/userProfile/components/profileHeader/mobileHeader.tsx
> +  const username = type === 'users' ? `@${(identity as User).username}` : `@${(identity as Organization).shortname}`;
Same as above

2024-01-05 11:07 UTC, bastantebom commented on src/Nowruz/modules/userProfile/containers/editImage/useEditImage.tsx
> +  };
```suggestion
  function updateIdentityImage(image: PostMediaUploadRes) {
  const updatedUser = { ...identity };

// `type` here is a param to the function so it should be accessible here
//  `identityType` should be available as well
  const imageProperty = type === 'avatar' ?
    (identityType === 'users' ? 'avatar' : 'image') :
    'cover_image';

  updatedUser[imageProperty] = image;

  const dispatchAction = identityType === 'users' ?
    store.dispatch(updateUserProfile(updatedUser as User)) :
    store.dispatch(updateOrgProfile(updatedUser as Organization));

  dispatchAction.then(async () => {
    await updateIdentityList();
    closeModal();
  });
}
```

2024-01-05 11:09 UTC, bastantebom requested changes
Some refactor changes for readability. Thanks!

2024-01-06 02:14 UTC, seira-yun commented on env.tmp
@bastantebom This is a .env file template. So that new devs can copy and paste these and add the tokens in their .env file.

2024-01-09 05:39 UTC, jeyem approved these changes

2024-01-09 12:39 UTC, bastantebom approved these changes
Looks good! Thanks

2024-01-09 22:37 UTC, merged