fix: design discrepancies and feedback for OP. My profile
socious-io/web-app-v2 pull request #335
Opened 2024-01-16 12:06 UTC by bastantebom

**Ticket:** [Bugs related to: OP. My profile: about tab (excluding all other tabs)](https://www.notion.so/socious/Bugs-related-to-OP-My-profile-about-tab-excluding-all-other-tabs-712b115117c04ba585626d26440e5403?pvs=4)

**Definition of done:**
- [x]  1. Figma includes data related to the “industry” and “size” - It was already implemented we just don't have data
- [x]  2. The website link should open in the new tab
- [x]  3. The hiring badge is not aligned on top on the same level as the name (please check Figma)(Minh feedback on GitHub)
- [x]  4. Share button missing spacing between icon and text(Minh feedback on GitHub)
- [x]  5. border missing for country flag(Minh feedback on GitHub)
- [x]  6. The cursor pointer missing on the "see more" hover(Minh feedback on GitHub)

**Media:**

https://github.com/socious-io/web-app-v2/assets/5590282/da62f96d-b2fe-4eb9-82ee-e164f59399af

2024-01-17 05:34 UTC, marjan-ara requested changes

2024-01-17 05:34 UTC, marjan-ara commented on src/Nowruz/modules/userProfile/components/profileHeader/desktopHeader.tsx
> +            >
Could you please replace inline style with customStyle and pass a className to this button? I think it has been my mistake

2024-01-17 19:59 UTC, marjan-ara approved these changes

2024-01-17 21:42 UTC, aziinz commented
@bastantebom The 
![Size](https://github.com/socious-io/web-app-v2/assets/108272273/569f33b3-afe7-4130-af93-cf36bf083724)
Size data is wrong

2024-01-18 02:54 UTC, bastantebom commented
> @bastantebom The ![Size](https://private-user-images.githubusercontent.com/108272273/297525918-569f33b3-afe7-4130-af93-cf36bf083724.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NDY3MTAsIm5iZiI6MTcwNTU0NjQxMCwicGF0aCI6Ii8xMDgyNzIyNzMvMjk3NTI1OTE4LTU2OWYzM2IzLWFmZTctNDEzMC1hZjkzLWNmMzZiZjA4MzcyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQwMjUzMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjJlYzMxMGY2NDRlNjMzZDM1ZTIwZDA2OTY0NjQxZDYzMzU5MDRlMWExNmZiN2NkZDJkZjFmNzAyZDUyMDczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bt15-y2wK14dh0-61D64u5-S7Wl2JzDcHRy96Mscx_E) Size data is wrong

I will check the current data.

2024-01-18 05:59 UTC, jeyem commented
> > @bastantebom The ![Size](https://private-user-images.githubusercontent.com/108272273/297525918-569f33b3-afe7-4130-af93-cf36bf083724.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NDY3MTAsIm5iZiI6MTcwNTU0NjQxMCwicGF0aCI6Ii8xMDgyNzIyNzMvMjk3NTI1OTE4LTU2OWYzM2IzLWFmZTctNDEzMC1hZjkzLWNmMzZiZjA4MzcyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQwMjUzMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjJlYzMxMGY2NDRlNjMzZDM1ZTIwZDA2OTY0NjQxZDYzMzU5MDRlMWExNmZiN2NkZDJkZjFmNzAyZDUyMDczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bt15-y2wK14dh0-61D64u5-S7Wl2JzDcHRy96Mscx_E) Size data is wrong
> 
> @aziinz I will check the current data.

@bastantebom we have constant for this please check constant file to find size mapping

2024-01-18 08:39 UTC, bastantebom commented
> > > @bastantebom The ![Size](https://private-user-images.githubusercontent.com/108272273/297525918-569f33b3-afe7-4130-af93-cf36bf083724.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NDY3MTAsIm5iZiI6MTcwNTU0NjQxMCwicGF0aCI6Ii8xMDgyNzIyNzMvMjk3NTI1OTE4LTU2OWYzM2IzLWFmZTctNDEzMC1hZjkzLWNmMzZiZjA4MzcyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQwMjUzMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjJlYzMxMGY2NDRlNjMzZDM1ZTIwZDA2OTY0NjQxZDYzMzU5MDRlMWExNmZiN2NkZDJkZjFmNzAyZDUyMDczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bt15-y2wK14dh0-61D64u5-S7Wl2JzDcHRy96Mscx_E) Size data is wrong
> > 
> > 
> > @aziinz I will check the current data.
> 
> @bastantebom we have constant for this please check constant file to find size mapping

@jeyem can you point me to the correct file where I can see this mapping, I couldn't find any relevant file. Thanks

2024-01-18 09:51 UTC, merged