TAS-1448/Remove-Delete-Member
socious-io/web-app-v2 pull request #550
Opened 2024-04-18 05:27 UTC by satanmourner

This branch includes two parts:
- User side: 
  - [ ] many members -> open modal (`Are you sure to leave the team?`)
  - [ ] one member -> open modal (show warning `can not leave the team` and give options to the user)
  
- Org side:
  - [ ] many members -> open modal (`Are you sure to delete this member?`) 
  
TODO:
- [ ] Add a new icon to the icon pack
- [ ] Ask BE for `teams.length` on one account
- [ ] Ask Marjan to fix (2 `FIXME`) in `orgTeam` file (ts errors)

2024-04-22 05:08 UTC, marjan-ara approved these changes

2024-04-24 05:55 UTC, seira-yun commented
Sanaz will fix it today.

2024-04-24 14:37 UTC, jeyem requested changes

2024-04-24 14:37 UTC, jeyem commented on src/core/api/site/site.types.ts
> +  identity_meta?: UserMeta;
```suggestion
  identity_meta: UserMeta | OrgMeta;
```

2024-04-24 15:14 UTC, jeyem approved these changes

2024-04-24 15:14 UTC, merged