TAS-532/OP-Create-job
socious-io/web-app-v2 pull request #560
Opened 2024-04-21 18:36 UTC by marjan-ara

2024-04-23 05:44 UTC, jeyem commented
@marjan-ara you may update tests snaps on your PR and resolve tests fails here

2024-05-07 06:34 UTC, satanmourner commented
@marjan-ara I know you are busy with AI recommendation feature but  whenever this PR is ready, mention me here. (don't hurry and worry about this PR)
and if it is completed, again please mention me to review.

2024-05-07 07:14 UTC, marjan-ara commented
@satanmourner It is ready for review :)

2024-05-08 09:15 UTC, satanmourner requested changes

2024-05-11 15:05 UTC, satanmourner approved these changes

2024-05-11 15:06 UTC, merged