TAS-925/Feeds
socious-io/web-app-v2 pull request #627
Opened 2024-05-13 20:35 UTC by satanmourner

**This branch is related to part of the feeds feature, including:**
- [ ] feeds and access to feeds page
- [ ] creating a post
- [ ] showing posts
- [ ] like/comment posts
- [ ] repost a post
- [ ] like/reply to a comment

TODO:
- [ ] `logged-in` user can only access to feeds page
- [ ] check `ExpandableText` everywhere
- [ ] pre-defined emojis
- [ ] final check (test + clean code)
- [ ] record a video of the whole process (+another branch)

2024-05-22 06:41 UTC, marjan-ara requested changes

2024-05-22 06:41 UTC, marjan-ara commented on src/Nowruz/modules/feeds/feedItem/index.types.ts
I think here a wrong value is passed to userImg, it shoud be currentIdentity image instead of creator image
`   <SendBox
                    name="comment"
                    userImg={(profileImage as string) || ''}
                    placeholder="Comment..."
                    value={comment}
                    onChange={value => setComment(value)}
                    onEmojiSelect={emoji => setComment(prev => prev + emoji)}
                    onSend={onSendComment}
                  />`

2024-05-22 09:56 UTC, satanmourner commented on src/Nowruz/modules/feeds/contexts/feeds.context.tsx
> +
it's not a global state across applications and it's the wrong approach to use `redux` when we wanna drill props between parents and children. it is overkill and better use `Context APi`

2024-05-22 11:16 UTC, satanmourner commented
I found a small bug in reaction emojis, whenever it resolved I will make ready PR again and I will request Marjan to review all her changes and these changes too

2024-05-25 06:01 UTC, marjan-ara approved these changes

2024-05-26 20:46 UTC, merged