TAS-2295/event dashboard banner
socious-io/web-app-v2 pull request #809
Opened 2024-08-01 03:21 UTC by marjan-ara

2024-08-01 09:08 UTC, satanmourner requested changes

2024-08-01 09:08 UTC, satanmourner commented on src/modules/general/components/topBanner/index.tsx
> +      className={`w-full pb-2 p-4 xl:px-6 ${theme === 'purple' ? 'xl:py-3' : 'xl:py-1'} flex flex-col xl:flex-row xl:items-center justify-between gap-2`}
I knew this condition was for just a 'purple' theme but can't we tell Minh to make a consistent style for all banners?

2024-08-01 09:18 UTC, satanmourner commented on src/modules/general/components/topBanner/index.tsx
> +      className={`w-full pb-2 p-4 xl:px-6 ${theme === 'purple' ? 'xl:py-3' : 'xl:py-1'} flex flex-col xl:flex-row xl:items-center justify-between gap-2`}
otherwise please define a prop for making different styles from outside of component.

2024-08-05 05:13 UTC, satanmourner requested changes

2024-08-05 05:43 UTC, marjan-ara commented on src/pages/dashboard/useDashborad.tsx
> +    localStorage.setItem('filter', JSON.stringify(filter));
I didn't change this part, but I checked and whenever user is redirected to the search page, filter is removed. Clicking on navigation items (including logout) also removes filter. It seems it is working properly

2024-08-05 08:55 UTC, satanmourner approved these changes

2024-08-05 08:55 UTC, merged